org: georgedavis
app: deepsecurity-migration-assistant
service: deepsecurity-migration-assistant

frameworkVersion: '3'

custom:
  defaultStage: dev
  stages:
    dev:
      awscli_profile: default
      aws_region: us-east-2
      srcC1WSApiKey: <source_cloudone_api_key>
      destC1WSApiKey: <destination_cloudone_api_key>
      exceptionPolicies: Base Policy, Demo, LAMP Server, Linux Server, Windows, Windows Server 2003, Windows Server 2008, Windows Server 2012
    staging:
      awscli_profile: staging
      aws_region: us-east-1
      srcC1WSApiKey: <source_cloudone_api_key>
      destC1WSApiKey: <destination_cloudone_api_key>
      exceptionPolicies: Base Policy, Demo, LAMP Server, Linux Server, Windows, Windows Server 2003, Windows Server 2008, Windows Server 2012

provider:
  name: aws
  runtime: python3.8
  profile: ${self:custom.stages.${opt:stage}.awscli_profile}
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.stages.${opt:stage}.aws_region}
  memorySize: 128
  timeout: 180
  environment:
    srcC1WSApiKey: ${self:custom.stages.${opt:stage}.srcC1WSApiKey}
    destC1WSApiKey: ${self:custom.stages.${opt:stage}.destC1WSApiKey}    
  tags:
    BusinessCase: C1WS-MigrationAssistant
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/deepsecurity-migration-assistant.git
  stackTags:
    BusinessCase: C1WS-MigrationAssistant
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/deepsecurity-migration-assistant.git
  iam:
    role:
      name: deepsecurity-migration-assistant-${opt:stage, self:custom.defaultStage}
      path: /
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - 'logs:*'
      tags:
        BusinessCase: C1WS-MigrationAssistant
        Owner: TrendMicro
        CodeSource: https://github.com/GeorgeDavis-TM/deepsecurity-migration-assistant.git
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: handler.main
    description: DeepSecurity Migration Assistant

